In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('risco-credito.csv')

In [3]:
base

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12          boa    alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

In [4]:
previsores = base.iloc[:,0:4].values

In [5]:
previsores

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa ', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [6]:
classe = base.iloc[:,4].values

In [7]:
# tranformar as variaveis categoricas em numericas
# LabelEnconder pega uma variavel categorica e transforma e numeros
# OneHotEncoder trabalho com variaveis tipo Dummy
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

previsores[:, 0] = labelencoder.fit_transform(previsores[:, 0])
previsores[:, 1] = labelencoder.fit_transform(previsores[:, 1])
previsores[:, 2] = labelencoder.fit_transform(previsores[:, 2])
previsores[:, 3] = labelencoder.fit_transform(previsores[:, 3])


In [32]:
previsores

array([[3L, 0L, 1L, 0L],
       [2L, 0L, 1L, 1L],
       [2L, 1L, 1L, 1L],
       [2L, 1L, 1L, 2L],
       [2L, 1L, 1L, 2L],
       [2L, 1L, 0L, 2L],
       [3L, 1L, 1L, 0L],
       [3L, 1L, 0L, 2L],
       [0L, 1L, 1L, 2L],
       [0L, 0L, 0L, 2L],
       [0L, 0L, 1L, 0L],
       [0L, 0L, 1L, 1L],
       [1L, 0L, 1L, 2L],
       [3L, 0L, 1L, 1L]], dtype=object)

In [8]:
#importando classe do algoritimo naive bayes
from sklearn.naive_bayes import GaussianNB

In [9]:
#criando um classificador que recebe o GaussianNB
classificador = GaussianNB()

In [10]:
#informar os parametros (previsores e a classe)
classificador.fit(previsores, classe)

GaussianNB(priors=None)

In [13]:
#metodo de teste do algoritimo

#historia de crdito = 0 boa
#divida = alta  0 
#garantias = 1 nenhuma
#renda = 2 renda maior que 35

resultado = classificador.predict([0,0,1,2])

C:\ProgramData\Anaconda2\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [15]:
resultado

array(['baixo'], 
      dtype='|S8')

# correcao laplaciana

In [18]:
# historia = ruim 3
#divida = alta 0
#garantias adequada 0
#renda =<15 0

In [21]:
resultado = classificador.predict([[0,0,1,2], [3,0,0,0]])

In [23]:
resultado

array(['baixo', 'moderado'], 
      dtype='|S8')

In [28]:
print(classificador.classes_)#imprime todas as classes

['alto' 'baixo' 'moderado']


In [30]:
print(classificador.class_count_)#quantidade de todas as classes

[ 6.  5.  3.]


In [31]:
print(classificador.class_prior_) #propabilidades apriori
#Probabilidade atribuída a um ou mais eventos antes da obtenção de informações experimentais ou amostrais, ou seja, independente da realização do experimento.
#Inglês: A Priori Probability

[ 0.42857143  0.35714286  0.21428571]
